version: '3.8'

services:
  backend:
    build: ./Backend
    image: backend
    container_name: backend
    expose:
      - "8000"
    volumes:
      - ./Backend:/app
    env_file:
      - .env
    environment:
      - ELASTIC_CLIENT_APIVERSIONING=true
    networks:
      - transcendence
    depends_on:
      postgres:
        condition: service_healthy
      blockchain:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    build: ./Infrastructure/postgres
    image: postgres
    container_name: postgres
    expose:
      - "5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - transcendence
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 5
    restart: unless-stopped

  blockchain:
    build: ./Blockchain
    image: blockchain
    container_name: blockchain
    expose:
      - "8545"
    ports:
      - "8545:8545"
    volumes:
      - blockchain:/etc/ethereum/Pong
    networks:
      - transcendence
    healthcheck:
      test: ["CMD", "ping", "-c", "1", "localhost:8545"]
      interval: 30s
      timeout: 30s
      retries: 5
    restart: unless-stopped

  nginx:
    build: ./Infrastructure/nginx
    image: nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ssl:/etc/nginx/ssl
    depends_on:
      - backend
      - frontend
    networks:
      - transcendence
    restart: unless-stopped

  frontend:
    build: ./Frontend
    image: frontend
    container_name: frontend
    expose:
      - "3000"
    volumes:
      - ./Frontend:/app
    networks:
      - transcendence
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 30s
      retries: 15
    restart: unless-stopped


  elasticsearch:
    build: ./Infrastructure/elasticsearch
    image: elk
    container_name: elk
    ports:
      - "9200:9200"
    volumes:
      - elk:/usr/share/elasticsearch/data
    env_file:
      - .env
    environment:
      - discovery.type=single-node
      - ELASTIC_CLIENT_APIVERSIONING=true
    networks:
      - transcendence
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health"]
      interval: 30s
      timeout: 30s
      retries: 15
    restart: unless-stopped

  kibana:
    build: ./Infrastructure/kibana
    image: kibana
    container_name: kibana
    expose:
      - "5601"
    volumes:
      - kibana:/usr/share/kibana
    env_file:
      - .env
    environment:
      - ELASTICSEARCH_HOSTS=http://elk:9200
      - SERVER_NAME=kibana
      - SERVER_HOST="0.0.0.0"
      - SERVER_BASEPATH=/kibana
      - SERVER_REWRITEBASEPATH=true
      - SERVER_PUBLICBASEURL=https://localhost/kibana
    networks:
      - transcendence
    depends_on:
      elasticsearch:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres:
    name: postgres
  ssl: 
    name: ssl
  elk:
    name: elk
  kibana:
    name: kibana
  blockchain:
    name: eth



networks:
  transcendence:
    name: transcendence
    driver: bridge