# Generated by Django 5.2 on 2025-04-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1Name', models.CharField(max_length=150)),
                ('player2Name', models.CharField(max_length=150)),
                ('player1Score', models.IntegerField()),
                ('player2Score', models.IntegerField()),
                ('matchType', models.CharField(choices=[('1 vs 1', '1 vs 1'), ('1 vs AI', '1 vs AI'), ('multiplyer', 'multiplyer'), ('tournament', 'tournament')], max_length=150)),
                ('winner', models.CharField(choices=[('player1', 'Player 1'), ('player2', 'Player 2')], max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matches', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
    ]
