# Generated by Django 5.2 on 2025-04-26 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevokedAccessToken',
            fields=[
                ('token', models.TextField(help_text='The full string of the revoked JWT Access Token.', primary_key=True, serialize=False, unique=True)),
                ('revoked_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the token was revoked.')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revoked_access_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Revoked Access Token',
                'verbose_name_plural': 'Revoked Access Tokens',
                'ordering': ['-revoked_at'],
            },
        ),
    ]
