name: Django & JS CI

on:
  push:
    branches: [ main, "*" ]
  pull_request:
    branches: [ main, "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build and start backend and postgres
        run: |
          docker compose up -d backend postgres

      - name: Wait for backend to be healthy
        run: |
          docker compose exec backend bash -c "until pg_isready -h postgres -U $POSTGRES_USER; do sleep 1; done"

      - name: Run Django users app tests in backend container
        run: |
          docker compose exec backend python manage.py test users

      - name: Show backend logs on failure
        if: failure()
        run: docker compose logs backend
