name: Django & JS CI

on:
  push:
    branches: [ main, "*" ]
  pull_request:
    branches: [ main, "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create .env file for CI
        run: |
          cat <<EOF > .env
          # Django Settings
          DJANGO_SECRET_KEY=testsecretkey
          DJANGO_DEBUG=True
          DJANGO_ALLOWED_HOSTS=*

          # Django Superuser
          DJANGO_SUPERUSER_USERNAME=admin
          DJANGO_SUPERUSER_EMAIL=admin@example.com
          DJANGO_SUPERUSER_PASSWORD=adminpass

          # Database Settings
          POSTGRES_DB=transcendence
          POSTGRES_USER=postgres
          POSTGRES_PASSWORD=postgres
          POSTGRES_HOST=postgres
          POSTGRES_PORT=5432

          # 42 OAuth Settings
          FT_CLIENT_ID=dummyclientid
          FT_CLIENT_SECRET=dummysecret
          FT_REDIRECT_URI=http://localhost/oauth/callback
          EOF

      - name: Build and start backend and postgres
        run: |
          docker compose up -d backend postgres

      - name: Wait for backend to be healthy
        run: |
          docker compose exec backend /bin/sh -c "until pg_isready -h postgres -U postgres; do sleep 1; done"

      - name: Run Django migrations in backend container
        run: |
          docker compose exec backend python3 manage.py migrate

      - name: Run Django users app tests in backend container
        run: |
          docker compose exec backend python3 manage.py test users.tests_register --verbosity=2
          docker compose exec backend python3 manage.py test users.tests_login.LoginViewTests --verbosity=2
          docker compose exec backend python3 manage.py test users.tests_2fa --verbosity=2

      - name: Show backend logs on failure
        if: failure()
        run: docker compose logs backend
